apiVersion: v1
kind: ConfigMap
metadata:
  name: terrabia-global-config
  namespace: terrabia
data:
  SPRING_CLOUD_CONFIG_URI: "http://terra-conf-service.terrabia.svc.cluster.local:8080"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://terra-registry-service.terrabia.svc.cluster.local:8761/eureka"
  EUREKA_CLIENT_ENABLED: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:5173"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  GIT_SSL_NO_VERIFY: "true"
  SPRING_CLOUD_CONFIG_SERVER_GIT_SKIP_SSL_VALIDATION: "true"
  SPRING_CLOUD_CONFIG_SERVER_GIT_REFRESH_RATE: "5"
