apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: terrabia
type: Opaque
stringData:
  mysql-root-password: "root"
  mysql-user: "terabia_user"
  mysql-password: "terabia_password"
  postgres-user: "delphan"
  postgres-password: "mypassword"
  postgres-orders-user: "terra_user"
  postgres-orders-password: "terra_password"
  django-secret-key: "terra-order-secret-key-2024-change-in-production"
  rabbitmq-user: "guest"
  rabbitmq-password: "guest"
  notification-mysql-user: "terra_notification_user"
  notification-mysql-password: "notification_password"

